### ISSUE TITLE
Reproduce Results

### ISSUE THREAD

**Issue by Areeb2735** [JiazuoYu/MoE-Adapters4CL#12]
Hi.

I am unable to reproduce the results for the MDTL setting. I am running this bash file,  srcipts/train/train_full_shot_router11_experts22_1000iters.sh. Am I missing something? The results are noticeably different. I am comparing with table 9 from the paper. Please do let me know. 

Thank you.

**Comment by JiazuoYu** [comment]
Hi,
 
Could you please provide further settings and results? 
In addition, you can check whether the DDAS training is correct. You can use the ckpts we provide to check the problems of the two parts of DDAS or MoE-Adapter that you reproduced.

**Comment by Areeb2735** [comment]
![Screenshot 2024-07-17 at 11 13 05 AM](https://github.com/user-attachments/assets/be60bec3-bdc3-4813-bce1-6646571f0f7f)

The results are almost the same except for the zero-shot on Cifar100 and EuroSAT (in the first row). Please find attached the screenshot of the results. 

I train using the default setting, 
bash srcipts/train/train_full_shot_router11_experts22_1000iters.sh

Thank you in advance.

**Comment by JiazuoYu** [comment]
Hi,

Apologies for the delayed response. We reran the experiments and found the results still similar to those in the paper. The retrained and tested results are as follows:
<img width="734" alt="截屏2024-07-18 01 19 53" src="https://github.com/user-attachments/assets/bb960272-696b-4be8-968a-d996f2977720">

Upon careful review, we discovered an error in the code organization due to incorrect copying. You can refer to #13, and we have updated the repository accordingly.

We deeply regret any inconvenience caused by our oversight. Thank you.

**Comment by Areeb2735** [comment]
Thank you for your response. I have corrected the code, as you said. Please find attached the results table. The Results are different from what you are reporting. For instance, the first row gives me 53.53%, while it's 50.08% for you. Also, the zero-shot on cigar and erurosat is too different. I have also attached the arguments list I am using. 

<img width="787" alt="image" src="https://github.com/user-attachments/assets/2ea8bc06-b0fb-4495-a65d-792a12d7d0a3">

<img width="996" alt="image" src="https://github.com/user-attachments/assets/d461a354-7d36-440a-9bbc-3d919c73efa7">


Thank you again.

**Comment by JiazuoYu** [comment]
For zeroshot performance, you can adjust the different thresholds to check the results of zeroshot. 

Regarding the fluctuation of results, we think it is inevitable.
