### ISSUE TITLE
About CIL

### ISSUE THREAD

**Issue by boringKey** [JiazuoYu/MoE-Adapters4CL#9]
This is truly an excellent piece of work. However, I have a question for you. In the class incremental setting, how does utilizing only one router combined with two experts address the problem of catastrophic forgetting? Specifically, the experts can only retain knowledge of the current classes and cannot store knowledge of previous classes. I look forward to your explanation.

**Comment by JiazuoYu** [comment]
For class-incremental learning (CIL) tasks, when only 1 route and 2 experts are used without a frozen activation strategy, repeated learning of network parameters indeed leads to forgetting. However, we were surprised to find that as the number of experts increases, the routing tends to learn specific expert combinations for similar classes. We think it alleviates the parameter changes caused by jointly training classes of significantly different distributions within the same group of experts, thereby alleviating the forgetting phenomenon. This finding also indirectly demonstrates that expert models have some inherent advantages in handling different distribution data and incremental learning tasks.
